name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # atau branch utama Anda

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # atau versi Node.js yang Anda gunakan

      - name: Install dependencies (if any)
        run: npm install # atau yarn install, pnpm install

      - name: Replace environment variables
        run: |
          # Cukup panggil nama filenya saja karena sudah di 'Checkout'
          sed -i "s#const SHEET_URL = '.*'#const SHEET_URL = '${{ secrets.SHEET_URL }}'#g" style.js

      - name: Build (if any)
        run: npm run build # atau perintah build Anda

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # atau direktori build Anda
